# Generated by Django 4.2.28 on 2026-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=512)),
                ('to_address', models.TextField(blank=True)),
                ('cc', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('envelope', models.JSONField(blank=True, default=dict)),
                ('attachment_info', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inbound Email',
                'verbose_name_plural': 'Inbound Emails',
                'ordering': ['-received_at'],
            },
        ),
    ]
