# Generated by Django 4.2.28 on 2026-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_add_inbound_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='amount_to_invest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='email_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='listing_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='purchase_timeframe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='raw_parsed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='time_horizon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
