# Generated by Django 4.2.28 on 2026-02-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0002_add_parsed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='lead_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='lead_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='listing_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='listing_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='original_email_message_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
