# Generated by Django 4.2.28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_lead_extraction_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboundemail',
            old_name='buyer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inboundemail',
            old_name='buyer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='inboundemail',
            old_name='buyer_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='inboundemail',
            old_name='listing_title',
            new_name='listing_name',
        ),
    ]
