# Generated by Django 4.2.28 on 2026-02-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_rename_buyer_to_name_listing_title_to_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
